import { formatReceiptDateTime, type TransferReceiptData } from "@/lib/transfer-receipt";

function formatAmount(amount: number) {
  const n = Number(amount);
  if (!Number.isFinite(n) || n < 0) return "NGN 0.00";
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    minimumFractionDigits: 2,
  }).format(n);
}

type JsPDFConstructor = new (options?: { unit?: string; format?: string }) => {
  internal: { pageSize: { getWidth: () => number } };
  setFont: (family: string, style: string) => void;
  setFontSize: (size: number) => void;
  setTextColor: (r: number, g: number, b: number) => void;
  setFillColor: (r: number, g: number, b: number) => void;
  text: (text: string | string[], x: number, y: number) => void;
  rect: (x: number, y: number, w: number, h: number, style?: string) => void;
  line: (x1: number, y1: number, x2: number, y2: number) => void;
  setDrawColor: (r: number, g: number, b: number) => void;
  splitTextToSize: (text: string, maxWidth: number) => string[];
  save: (filename: string) => void;
};

async function loadJsPDF(): Promise<JsPDFConstructor> {
  try {
    const mod = await import("jspdf");
    console.log("[SafeBank] jsPDF loaded from package");
    return mod.jsPDF as unknown as JsPDFConstructor;
  } catch {
    console.log("[SafeBank] jsPDF package missing, loading from CDN...");
    return new Promise((resolve, reject) => {
      const w = window as Window & { jspdf?: { jsPDF: JsPDFConstructor } };
      if (w.jspdf?.jsPDF) {
        resolve(w.jspdf.jsPDF);
        return;
      }
      const script = document.createElement("script");
      script.src = "https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js";
      script.async = true;
      script.onload = () => {
        if (w.jspdf?.jsPDF) {
          console.log("[SafeBank] jsPDF loaded from CDN");
          resolve(w.jspdf.jsPDF);
        } else {
          reject(new Error("jsPDF CDN load failed"));
        }
      };
      script.onerror = () => reject(new Error("jsPDF script failed to load"));
      document.head.appendChild(script);
    });
  }
}

export async function downloadReceiptPdf(data: TransferReceiptData) {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const isSuccess = data.status === "success" || data.status === "flagged";
  const amount = Number(data.amount) > 0 ? Number(data.amount) : 0;
  const margin = 48;
  let y = margin;

  const addLine = (
    text: string,
    size = 11,
    bold = false,
    color: [number, number, number] = [30, 30, 30]
  ) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(text, margin, y);
    y += size + 8;
  };

  doc.setFillColor(11, 16, 32);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 72, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("SafeBank AI", margin, 40);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Transaction Receipt", margin, 58);

  y = 96;

  const statusText = isSuccess
    ? data.status === "flagged"
      ? "Transfer sent — under review"
      : "Transfer successful"
    : `Transfer failed — ${data.failureTitle || "Error"}`;

  addLine(statusText, 14, true, isSuccess ? [24, 194, 156] : [239, 68, 68]);

  y += 4;
  addLine("Amount", 10, false, [100, 116, 139]);
  addLine(formatAmount(amount), 22, true);

  y += 8;
  const rows: [string, string][] = [
    ["Recipient", data.recipientName || "—"],
    ["Account number", data.recipientAccount || "—"],
    ["Reference", data.reference || "—"],
    ["Date & time", formatReceiptDateTime(data.createdAt)],
    ["Transaction type", "Transfer to SafeBank AI"],
    ["Payment method", "SafeBank AI Balance"],
  ];

  if (isSuccess && data.newBalance != null) {
    rows.push(["Balance after transfer", formatAmount(data.newBalance)]);
  }
  if (!isSuccess && data.availableBalance != null) {
    rows.push(["Available balance", formatAmount(data.availableBalance)]);
  }
  if (!isSuccess && data.failureReason) {
    rows.push(["Reason", data.failureReason]);
  }

  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    const wrapped = doc.splitTextToSize(value, 280);
    doc.text(wrapped, 220, y);
    y += Math.max(18, wrapped.length * 12);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y - 6, doc.internal.pageSize.getWidth() - margin, y - 6);
  });

  y += 12;
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by SafeBank AI. Keep this receipt for your records.", margin, y);

  const filename = `safebank-receipt-${data.reference || data.status}.pdf`;
  doc.save(filename);
  console.log("[SafeBank] PDF receipt downloaded:", filename);
}
